#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/create_network
- name: Create Docker network
  docker_network:
    name: my_app_network
    driver: bridge
    ipam_config:
      - subnet: 192.168.1.0/24
    appends: false
    state: present
    use_localhost: true
  vars:
    ansible_python_interpreter: /usr/bin/python3