#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/launch_proxy
- name: Launch proxy container
  docker_container:
    name: my_proxy
    image: nginx:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"
      - "443:443"
    network_mode: my_app_network
    volumes:
      - /srv/proxy/conf.d:/etc/nginx/conf.d